### ISSUE TITLE
Checks for ignored_det and ignored_gt in compute_statistics_jit()

### ISSUE THREAD

**Issue by shashankag14** [fnozarian/OpenPCDet#12]
`ignored_det` and `ignored_gt` are being assigned either 0 or -1 based on valid class index in `clean_data`

https://github.com/fnozarian/OpenPCDet/blob/d274fe0b6b6b023b90c6094794145d596821f298/pcdet/utils/stats_utils.py#L206-L228

However, in `compute_statistics_jit`, we are checking for some cases where `ignored_det==1` and `ignored_gt==1` 
https://github.com/fnozarian/OpenPCDet/blob/d274fe0b6b6b023b90c6094794145d596821f298/pcdet/utils/stats_utils.py#L284-L308

Is there any case, when these two values (`ignored_det` and `ignored_gt`) are assigned 1 ?

**Comment by danish87** [comment]
and here we are checking for ignored_det==1 or ignored_det==-1 https://github.com/fnozarian/OpenPCDet/blob/c5782fe114497ac9abe7dab156538bc59b22ca93/pcdet/utils/stats_utils.py#L304-L305

**Comment by fnozarian** [comment]
In original eval.py, `ignored_gt == 1` either when `valid_class == 0` e.g., when class is `Van` or `Person_sitting` but we don't have such invalid classes during training.  `Or` when the class is valid and ignored due to a higher difficulty than the current level. Currently, we don't deal with difficulty, so we don't ignore any GTs for that reason. Detections are also ignored when they don't fall into a certain difficulty level, which is not relevant currently. So, we shouldn't have any detections or groundthrouth set to 1. There are still leftover conditions in the code checking dets/gts for 1 from the original eval.py, but I suppose they don't hurt the logic.

**Comment by shashankag14** [comment]
> In original eval.py, `ignored_gt == 1` either when `valid_class == 0` e.g., when class is `Van` or `Person_sitting` but we don't have such invalid classes during training. `Or` when the class is valid and ignored due to a higher difficulty than the current level. Currently, we don't deal with difficulty, so we don't ignore any GTs for that reason. Detections are also ignored when they don't fall into a certain difficulty level, which is not relevant currently. So, we shouldn't have any detections or groundthrouth set to 1. There are still leftover conditions in the code checking dets/gts for 1 from the original eval.py, but I suppose they don't hurt the logic.

Thanks for the clarification. 

In that case, in **L296** we are currently updating TP irrespective of the fact that the classes in **GT** and **Pred** are valid or invalid. Do we need to modify this **L296** and add a check if the classes in both **GT** and **Pred** are **valid** before incrementing the TP ? 
Eg. `(valid_detection != NO_DETECTION and ignored_det==0 and ignored_gt==0)` instead of `(valid_detection != NO_DETECTION`
https://github.com/fnozarian/OpenPCDet/blob/d274fe0b6b6b023b90c6094794145d596821f298/pcdet/utils/stats_utils.py#L291-L301

**Comment by fnozarian** [comment]
Doesn't `ignored_det==0 and ignored_gt==0` always evaluate True there?
Considering that `valid_detection != NO_DETECTION` is True then the `ignored_gt` and `ignored_dt` cannot be 1 as discussed before. They also cannot be -1 since the `for`s `continue` in lines [L257](https://github.com/fnozarian/OpenPCDet/blob/d274fe0b6b6b023b90c6094794145d596821f298/pcdet/utils/stats_utils.py#L257) and [L265](https://github.com/fnozarian/OpenPCDet/blob/soft-teacher-reliable/pcdet/utils/stats_utils.py#L265), respectively.

**Comment by fnozarian** [comment]
> we also looked if we don't have any tp, then there is no threshold level saved. In that case, we won't be able to save fn. While in our previous stats implementation we were keeping record of fn even if we don't have tp
> 
> https://github.com/fnozarian/OpenPCDet/blob/c5782fe114497ac9abe7dab156538bc59b22ca93/pcdet/utils/stats_utils.py#L142-L169

That's a problem. I'll check the code.

**Comment by fnozarian** [comment]
> we also looked if we don't have any tp, then there is no threshold level saved. In that case, we won't be able to save fn. While in our previous stats implementation we were keeping record of fn even if we don't have tp
> 
> https://github.com/fnozarian/OpenPCDet/blob/c5782fe114497ac9abe7dab156538bc59b22ca93/pcdet/utils/stats_utils.py#L142-L169

Regarding this issue, if we have empty predictions, the calculated stats are correct as long as there's an example with some prediction. So we don't need to be worried about empty predictions because they will eventually get appended with predictions of other examples, and overall, the FN is calculated correctly, I think. To verify, you can make a case with 2 examples, one has a few predictions, and the other has no predictions. The final FN should have the FNs of the empty example as well.
